# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 393cb8406a0478f08d929393c7c3f35a22847a6334523034bb1f574e865709f0cc1f76c1e56c9f12618f240d3c77f18d0378b70bcd58d68541c28909fd2e1992

test:
  secret_key_base: 12035fb9b5d8fb8bb53d35b132d6f532d1b325564a39a506fe30deb5c405b890a623312854fc7638dd211bd0c95f735d3aa8cc666c962696e31028cffd0a8967

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
